version: '3' 
services: 
    jenkins: 
        image: jenkins/jenkins:lts-jdk11 
        
        volumes:
            - type: volume
              source: jenkins1
              target: /var/jenkins_home
        ports: 
            - 9090:8080
            - 50000:50000

volumes:
    jenkins1: